Repository Pandora-IsoMemo/data-tools, pull requests merged in 2023-05, with the labels that each got.

#41 add API_BASE_URL conditional to callAPI fct
  R/03-isomemoAPI.R
Labels: 2022-WP2-2

#42 Version 23.05.0: functions to update list names
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/03-updateListNamesIfDuplicate.R
  man/incIndexOfName.Rd
  man/updateListNamesIfDuplicate.Rd
  man/updateNameEntryIfDuplicate.Rd
  tests/testthat/test-updateListNamesIfDuplicate.R
Labels: 2022-WP2-8

#39 Version 23.05.01: merge several files
  DESCRIPTION
  NEWS.md
  R/02-importData-mergeData.R
  R/02-importData-prepareData.R
  R/02-importData-queryData.R
  R/02-importData-selectData.R
  R/02-importData.R
  R/03-showInfoUI.R
  README.md
  man/formatColumnNames.Rd
  man/prepareDataServer.Rd
  man/renameColumnsServer.Rd
  man/selectDataServer.Rd
  man/selectDataUI.Rd
  man/selectFileTypeServer.Rd
  man/selectFileTypeUI.Rd
  man/selectSourceServer.Rd
  man/selectSourceUI.Rd
  man/showInfoUI.Rd
  man/updateMergeList.Rd
  tests/testthat/alkane_database.xlsx
  tests/testthat/test-importData-mergeData.R
  tests/testthat/test-importData-queryData.R
  tests/testthat/test-importData-selectData.R
  tests/testthat/test-importData.R
Labels: 2022-WP2-2

#43 23.05.3: order and filter of ckan resources
  DESCRIPTION
  NEWS.md
  R/02-importData-selectData.R
  R/02-importData.R
  R/03-ckan.R
  man/getCKANResourcesChoices.Rd
  tests/testthat/test-ckan.R
  tests/testthat/test-importData-selectData.R
Labels: 2022-WP2-3

#46 Version: 23.05.5.2: Bug/update of ckan inputs
  DESCRIPTION
  R/01-toolsPanel.R
  R/02-importData-selectData.R
  R/02-importData.R
  R/03-ckan.R
  man/selectDataServer.Rd
  man/selectSourceServer.Rd
  tests/testthat/test-importData-selectData.R
Labels: bug
